// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperHero.Server;

#nullable disable

namespace SuperHero.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250429213639_SeedSuperPowers")]
    partial class SeedSuperPowers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeroSuperPower", b =>
                {
                    b.Property<int>("HeroisId")
                        .HasColumnType("int");

                    b.Property<int>("SuperPoderesId")
                        .HasColumnType("int");

                    b.HasKey("HeroisId", "SuperPoderesId");

                    b.HasIndex("SuperPoderesId");

                    b.ToTable("HeroSuperPower");
                });

            modelBuilder.Entity("SuperHero.Server.Models.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Altura")
                        .HasColumnType("float");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NomeHeroi")
                        .IsRequired()
                        .HasColumnType("nvarchar(120)");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("SuperHero.Server.Models.SuperPower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("SuperPoder")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SuperPowers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Voa para perto ou longe do adversário, melhorando ataques e esquivas.",
                            SuperPoder = "Voar"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Aumenta o dano do ataque realizado ao adversário.",
                            SuperPoder = "Super Força"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Dobra a velocidade de movimento.",
                            SuperPoder = "Super velocidade"
                        });
                });

            modelBuilder.Entity("HeroSuperPower", b =>
                {
                    b.HasOne("SuperHero.Server.Models.Hero", null)
                        .WithMany()
                        .HasForeignKey("HeroisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SuperHero.Server.Models.SuperPower", null)
                        .WithMany()
                        .HasForeignKey("SuperPoderesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
